/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "RiseApe企猿技术博客",
  "description": "Hello, 猿人们! 企猿博客，学习前端、后端知识，分享面试经验，分享工作中的问题和写一些技术分享，是一个互联网从业者值得收藏的网站。",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/about/Index/",
      "relativePath": "about/Index/README.md",
      "key": "v-cd9d6b86",
      "path": "/about/Index/",
      "headers": [
        {
          "level": 3,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "联系我",
          "slug": "联系我"
        }
      ]
    },
    {
      "title": "基础知识-git常用指令",
      "frontmatter": {},
      "regularPath": "/views/basic/note.html",
      "relativePath": "views/basic/note.md",
      "key": "v-171b1580",
      "path": "/views/basic/note.html",
      "headers": [
        {
          "level": 2,
          "title": "title1",
          "slug": "title1"
        },
        {
          "level": 2,
          "title": "title3",
          "slug": "title3"
        },
        {
          "level": 2,
          "title": "title3-01",
          "slug": "title3-01"
        },
        {
          "level": 2,
          "title": "small title",
          "slug": "small-title"
        }
      ]
    },
    {
      "title": "This is guide",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/views/",
      "relativePath": "views/README.md",
      "key": "v-794b7414",
      "path": "/views/",
      "headers": [
        {
          "level": 2,
          "title": "This is guide",
          "slug": "this-is-guide"
        },
        {
          "level": 3,
          "title": "title3",
          "slug": "title3"
        },
        {
          "level": 3,
          "title": "title3-01",
          "slug": "title3-01"
        },
        {
          "level": 2,
          "title": "small title",
          "slug": "small-title"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "快速上手 →",
        "actionLink": "/views/note/note",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present xxxxxx"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-66124e65",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "知识笔记",
        "items": [
          {
            "text": "基础知识",
            "link": "/views/basic/note"
          }
        ]
      },
      {
        "text": "关于我",
        "link": "/about/Index/"
      },
      {
        "text": "Github",
        "link": "https://github.com/starm328"
      }
    ],
    "sidebarDepth": 2,
    "sidebar": {
      "/views/": [
        {
          "title": "前端笔记",
          "children": [
            "basic/note.md"
          ]
        }
      ]
    }
  }
}